### ISSUE TITLE
Make a tag/release for PyHEP 2022 "proceedings"

### ISSUE THREAD

**Issue by eduardo-rodrigues** [JostMigenda/PyHEP2022#2]
Hello @JostMigenda, can you kindly prepare the tag/release so that I then use it to mint a DOI on Zenodo and attach it to the workshop "proceedings" https://zenodo.org/communities/pyhep2022? Advance thanks.

**Comment by JostMigenda** [comment]
Here you go: https://github.com/JostMigenda/PyHEP2022/releases/tag/v1.0

**Comment by eduardo-rodrigues** [comment]
Perfect, thank you.
